// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVs1CzgCJgd5TVwodyN5bsLZMB0XXFiT4',
    appId: '1:363102107768:web:f6e203fb6149eb4a4c558d',
    messagingSenderId: '363102107768',
    projectId: 'assist-fcb34',
    authDomain: 'assist-fcb34.firebaseapp.com',
    storageBucket: 'assist-fcb34.firebasestorage.app',
    measurementId: 'G-BJPH1BQKNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0yaTepby20fbSF2kjoDGV_4Xu8mQEAgk',
    appId: '1:363102107768:android:c86e3ff61a6f39dc4c558d',
    messagingSenderId: '363102107768',
    projectId: 'assist-fcb34',
    storageBucket: 'assist-fcb34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3rcNDEGOm5sBcj0atUKzsmNz-DOGlKHg',
    appId: '1:363102107768:ios:02b6c6c933c8c3c04c558d',
    messagingSenderId: '363102107768',
    projectId: 'assist-fcb34',
    storageBucket: 'assist-fcb34.firebasestorage.app',
    iosBundleId: 'com.kofi.assist',
  );

}